version: '3.9'

services:

  db:
    container_name: db_app
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db_app
    volumes:
    - ./src/main/resources:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
